on: [push]

jobs:
  convert-csvs:
    runs-on: ubuntu-latest
    name: Convert xlsx files to csvs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Convert to CSV
        uses: CanDIG/xlsx2csv-action@v2.0
        id: convert
        with:
          input_file: .
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: xlsx2csv bot
          message: "convert xlsx files to csvs"
          add: "*"
          ref: ${{env.GITHUB_REF}}